# https://github.com/elastic/elasticsearch-docker
FROM hub.c.163.com/good0206/elasticsearch-oss:6.2.4

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
