---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
elasticsearch.username: "kibana"　　　　 #kibana用户名
elasticsearch.password: "123456"　　　　  #kibana密码
#server.ssl.enabled: true
#server.ssl.key: /usr/share/kibana/cert.key
#server.ssl.certificate: /usr/share/kibana/cert.pem
xpack.security.enabled: true
xpack.security.cookieName: sid
xpack.security.encryptionKey: 6704b717a3d3474896781e4356084e8e
